---
abstract: 'exception handling for Throwable::Factory'
author:
  - 'Lucien Coffe <lcoffe@cpan.org>'
build_requires:
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.140640'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Throwable-Factory-Try
no_index:
  directory:
    - t
    - inc
requires:
  Sub::Import: '1.001'
  Throwable::Factory: '0.006'
  Try::Tiny: '0.22'
  perl: '5.010000'
version: '0.03'
